// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/transbase.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TransBase {

  /// <summary>Holder for reflection information generated from proto/transbase.proto</summary>
  public static partial class TransbaseReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/transbase.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TransbaseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVwcm90by90cmFuc2Jhc2UucHJvdG8SCVRyYW5zQmFzZRoScHJvdG9idWYv",
            "YW55LnByb3RvIpIBCghUcmFuc1JlcRILCgNzaWQYASABKAMSCwoDb3B0GAIg",
            "ASgFEgwKBGRhdGEYAyABKAkSDAoEdmVycxgEIAEoCRINCgV0aW1lcxgFIAEo",
            "AxILCgNjaWQYBiABKAkSCwoDYnRzGAcgASgMEicKCWV4dGVuc2lvbhgIIAEo",
            "CzIULmdvb2dsZS5wcm90b2J1Zi5BbnkilAEKCFRyYW5zUmVzEgsKA3NpZBgB",
            "IAEoAxILCgNvcHQYAiABKAUSDAoEZGF0YRgDIAEoCRILCgNtc2cYBCABKAkS",
            "DQoFdGltZXMYBSABKAMSCwoDYnRzGAYgASgMEg4KBnJlc3VsdBgHIAEoCBIn",
            "CglleHRlbnNpb24YCCABKAsyFC5nb29nbGUucHJvdG9idWYuQW55YgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TransBase.TransReq), global::TransBase.TransReq.Parser, new[]{ "Sid", "Opt", "Data", "Vers", "Times", "Cid", "Bts", "Extension" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TransBase.TransRes), global::TransBase.TransRes.Parser, new[]{ "Sid", "Opt", "Data", "Msg", "Times", "Bts", "Result", "Extension" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TransReq : pb::IMessage<TransReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TransReq> _parser = new pb::MessageParser<TransReq>(() => new TransReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TransReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TransBase.TransbaseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransReq(TransReq other) : this() {
      sid_ = other.sid_;
      opt_ = other.opt_;
      data_ = other.data_;
      vers_ = other.vers_;
      times_ = other.times_;
      cid_ = other.cid_;
      bts_ = other.bts_;
      extension_ = other.extension_ != null ? other.extension_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransReq Clone() {
      return new TransReq(this);
    }

    /// <summary>Field number for the "sid" field.</summary>
    public const int SidFieldNumber = 1;
    private long sid_;
    /// <summary>
    /// 请求标识
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Sid {
      get { return sid_; }
      set {
        sid_ = value;
      }
    }

    /// <summary>Field number for the "opt" field.</summary>
    public const int OptFieldNumber = 2;
    private int opt_;
    /// <summary>
    /// 操作类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Opt {
      get { return opt_; }
      set {
        opt_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 3;
    private string data_ = "";
    /// <summary>
    /// 数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "vers" field.</summary>
    public const int VersFieldNumber = 4;
    private string vers_ = "";
    /// <summary>
    /// 版本
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Vers {
      get { return vers_; }
      set {
        vers_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "times" field.</summary>
    public const int TimesFieldNumber = 5;
    private long times_;
    /// <summary>
    /// 时间戳
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Times {
      get { return times_; }
      set {
        times_ = value;
      }
    }

    /// <summary>Field number for the "cid" field.</summary>
    public const int CidFieldNumber = 6;
    private string cid_ = "";
    /// <summary>
    /// 客户端id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Cid {
      get { return cid_; }
      set {
        cid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bts" field.</summary>
    public const int BtsFieldNumber = 7;
    private pb::ByteString bts_ = pb::ByteString.Empty;
    /// <summary>
    /// 二进制
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Bts {
      get { return bts_; }
      set {
        bts_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "extension" field.</summary>
    public const int ExtensionFieldNumber = 8;
    private global::Google.Protobuf.WellKnownTypes.Any extension_;
    /// <summary>
    /// 扩展
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any Extension {
      get { return extension_; }
      set {
        extension_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TransReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TransReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Sid != other.Sid) return false;
      if (Opt != other.Opt) return false;
      if (Data != other.Data) return false;
      if (Vers != other.Vers) return false;
      if (Times != other.Times) return false;
      if (Cid != other.Cid) return false;
      if (Bts != other.Bts) return false;
      if (!object.Equals(Extension, other.Extension)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Sid != 0L) hash ^= Sid.GetHashCode();
      if (Opt != 0) hash ^= Opt.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (Vers.Length != 0) hash ^= Vers.GetHashCode();
      if (Times != 0L) hash ^= Times.GetHashCode();
      if (Cid.Length != 0) hash ^= Cid.GetHashCode();
      if (Bts.Length != 0) hash ^= Bts.GetHashCode();
      if (extension_ != null) hash ^= Extension.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Sid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Sid);
      }
      if (Opt != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Opt);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Data);
      }
      if (Vers.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Vers);
      }
      if (Times != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Times);
      }
      if (Cid.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Cid);
      }
      if (Bts.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(Bts);
      }
      if (extension_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Extension);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Sid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Sid);
      }
      if (Opt != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Opt);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Data);
      }
      if (Vers.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Vers);
      }
      if (Times != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Times);
      }
      if (Cid.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Cid);
      }
      if (Bts.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(Bts);
      }
      if (extension_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Extension);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Sid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Sid);
      }
      if (Opt != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Opt);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Data);
      }
      if (Vers.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Vers);
      }
      if (Times != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Times);
      }
      if (Cid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cid);
      }
      if (Bts.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Bts);
      }
      if (extension_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Extension);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TransReq other) {
      if (other == null) {
        return;
      }
      if (other.Sid != 0L) {
        Sid = other.Sid;
      }
      if (other.Opt != 0) {
        Opt = other.Opt;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      if (other.Vers.Length != 0) {
        Vers = other.Vers;
      }
      if (other.Times != 0L) {
        Times = other.Times;
      }
      if (other.Cid.Length != 0) {
        Cid = other.Cid;
      }
      if (other.Bts.Length != 0) {
        Bts = other.Bts;
      }
      if (other.extension_ != null) {
        if (extension_ == null) {
          Extension = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Extension.MergeFrom(other.Extension);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Sid = input.ReadInt64();
            break;
          }
          case 16: {
            Opt = input.ReadInt32();
            break;
          }
          case 26: {
            Data = input.ReadString();
            break;
          }
          case 34: {
            Vers = input.ReadString();
            break;
          }
          case 40: {
            Times = input.ReadInt64();
            break;
          }
          case 50: {
            Cid = input.ReadString();
            break;
          }
          case 58: {
            Bts = input.ReadBytes();
            break;
          }
          case 66: {
            if (extension_ == null) {
              Extension = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Extension);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Sid = input.ReadInt64();
            break;
          }
          case 16: {
            Opt = input.ReadInt32();
            break;
          }
          case 26: {
            Data = input.ReadString();
            break;
          }
          case 34: {
            Vers = input.ReadString();
            break;
          }
          case 40: {
            Times = input.ReadInt64();
            break;
          }
          case 50: {
            Cid = input.ReadString();
            break;
          }
          case 58: {
            Bts = input.ReadBytes();
            break;
          }
          case 66: {
            if (extension_ == null) {
              Extension = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Extension);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TransRes : pb::IMessage<TransRes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TransRes> _parser = new pb::MessageParser<TransRes>(() => new TransRes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TransRes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TransBase.TransbaseReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransRes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransRes(TransRes other) : this() {
      sid_ = other.sid_;
      opt_ = other.opt_;
      data_ = other.data_;
      msg_ = other.msg_;
      times_ = other.times_;
      bts_ = other.bts_;
      result_ = other.result_;
      extension_ = other.extension_ != null ? other.extension_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransRes Clone() {
      return new TransRes(this);
    }

    /// <summary>Field number for the "sid" field.</summary>
    public const int SidFieldNumber = 1;
    private long sid_;
    /// <summary>
    /// 请求标识
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Sid {
      get { return sid_; }
      set {
        sid_ = value;
      }
    }

    /// <summary>Field number for the "opt" field.</summary>
    public const int OptFieldNumber = 2;
    private int opt_;
    /// <summary>
    /// 操作类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Opt {
      get { return opt_; }
      set {
        opt_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 3;
    private string data_ = "";
    /// <summary>
    /// 数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 4;
    private string msg_ = "";
    /// <summary>
    /// 版本
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Msg {
      get { return msg_; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "times" field.</summary>
    public const int TimesFieldNumber = 5;
    private long times_;
    /// <summary>
    /// 时间戳
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Times {
      get { return times_; }
      set {
        times_ = value;
      }
    }

    /// <summary>Field number for the "bts" field.</summary>
    public const int BtsFieldNumber = 6;
    private pb::ByteString bts_ = pb::ByteString.Empty;
    /// <summary>
    /// 二进制
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Bts {
      get { return bts_; }
      set {
        bts_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 7;
    private bool result_;
    /// <summary>
    /// 执行结果 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "extension" field.</summary>
    public const int ExtensionFieldNumber = 8;
    private global::Google.Protobuf.WellKnownTypes.Any extension_;
    /// <summary>
    /// 扩展参数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any Extension {
      get { return extension_; }
      set {
        extension_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TransRes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TransRes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Sid != other.Sid) return false;
      if (Opt != other.Opt) return false;
      if (Data != other.Data) return false;
      if (Msg != other.Msg) return false;
      if (Times != other.Times) return false;
      if (Bts != other.Bts) return false;
      if (Result != other.Result) return false;
      if (!object.Equals(Extension, other.Extension)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Sid != 0L) hash ^= Sid.GetHashCode();
      if (Opt != 0) hash ^= Opt.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (Msg.Length != 0) hash ^= Msg.GetHashCode();
      if (Times != 0L) hash ^= Times.GetHashCode();
      if (Bts.Length != 0) hash ^= Bts.GetHashCode();
      if (Result != false) hash ^= Result.GetHashCode();
      if (extension_ != null) hash ^= Extension.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Sid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Sid);
      }
      if (Opt != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Opt);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Data);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Msg);
      }
      if (Times != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Times);
      }
      if (Bts.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(Bts);
      }
      if (Result != false) {
        output.WriteRawTag(56);
        output.WriteBool(Result);
      }
      if (extension_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Extension);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Sid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Sid);
      }
      if (Opt != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Opt);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Data);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Msg);
      }
      if (Times != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Times);
      }
      if (Bts.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(Bts);
      }
      if (Result != false) {
        output.WriteRawTag(56);
        output.WriteBool(Result);
      }
      if (extension_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Extension);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Sid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Sid);
      }
      if (Opt != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Opt);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Data);
      }
      if (Msg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (Times != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Times);
      }
      if (Bts.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Bts);
      }
      if (Result != false) {
        size += 1 + 1;
      }
      if (extension_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Extension);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TransRes other) {
      if (other == null) {
        return;
      }
      if (other.Sid != 0L) {
        Sid = other.Sid;
      }
      if (other.Opt != 0) {
        Opt = other.Opt;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      if (other.Msg.Length != 0) {
        Msg = other.Msg;
      }
      if (other.Times != 0L) {
        Times = other.Times;
      }
      if (other.Bts.Length != 0) {
        Bts = other.Bts;
      }
      if (other.Result != false) {
        Result = other.Result;
      }
      if (other.extension_ != null) {
        if (extension_ == null) {
          Extension = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Extension.MergeFrom(other.Extension);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Sid = input.ReadInt64();
            break;
          }
          case 16: {
            Opt = input.ReadInt32();
            break;
          }
          case 26: {
            Data = input.ReadString();
            break;
          }
          case 34: {
            Msg = input.ReadString();
            break;
          }
          case 40: {
            Times = input.ReadInt64();
            break;
          }
          case 50: {
            Bts = input.ReadBytes();
            break;
          }
          case 56: {
            Result = input.ReadBool();
            break;
          }
          case 66: {
            if (extension_ == null) {
              Extension = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Extension);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Sid = input.ReadInt64();
            break;
          }
          case 16: {
            Opt = input.ReadInt32();
            break;
          }
          case 26: {
            Data = input.ReadString();
            break;
          }
          case 34: {
            Msg = input.ReadString();
            break;
          }
          case 40: {
            Times = input.ReadInt64();
            break;
          }
          case 50: {
            Bts = input.ReadBytes();
            break;
          }
          case 56: {
            Result = input.ReadBool();
            break;
          }
          case 66: {
            if (extension_ == null) {
              Extension = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Extension);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
